### ISSUE TITLE
ResultsTable value classes

### ISSUE THREAD

**Issue by tischi** [clij/clijx-weka#2]
Hi @haesleinhuepf 

This is not an issue, but a question.

IJ `ResultsTable` can have both `Double` and `String` values. I assume [your code](
https://github.com/clij/clijx-weka/blob/master/src/main/java/net/haesleinhuepf/clijx/weka/ApplyWekaToTable.java) _only_ accepts Double type table entries, is it?

**Comment by haesleinhuepf** [comment]
Yes, correct :-)

**Comment by tischi** [comment]
OK! Makes sense I guess!
